name 'tomcat'
maintainer 'Patrick Dayton'
maintainer_email 'daytonpa@gmail.com'
license 'all_rights'
description 'Installs/Configures tomcat'
long_description 'Installs/Configures tomcat'
version '0.1.0'
